### ISSUE TITLE
dotnet core version of FeatureSwitcher

### ISSUE THREAD

**Issue by stefc** [mexx/FeatureSwitcher#10]
I really want this lib for the .Net Core Framework. 
[https://www.microsoft.com/net/core](url)

The best would be that it have very few dependencies to other libs and following the .NET Standard Platform Version 1.6
[https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md](url)

**Comment by mexx** [comment]
At a quick look on the document your referenced, the library should be able to target `netstandard1.0`.
Thanks again for the #11

**Comment by mexx** [comment]
Closed by #17
