### ISSUE TITLE
Link FeatureSwitcher.VstsConfiguration

### ISSUE THREAD

**Issue by wulfland** [mexx/FeatureSwitcher#13]
I created a plugin that stores the config in Visual Studio Team Services (VSTS) as a workitem. Please add a link to the project in your readme.
Project: [FeatureSwitcher.VstsConfiguration](https://github.com/AlegriGroup/FeatureSwitcher.VstsConfiguration)
NuGet: [FeatureSwitcher.VstsConfiguration](https://www.nuget.org/packages/FeatureSwitcher.VstsConfiguration/)

**Comment by mexx** [comment]
Interesting way of configuration 👍

Link added in 459d001f1a.
